### PR TITLE
fix(internal/librarian/java): Improve error handling in generate.go and add back test case

### LINKED ISSUE #4436: java: refactor errors in java/generate.go
Going to differ to a followup to refactor Errors in [internal/librarian/java/generate.go](https://github.com/googleapis/librarian/pull/4381/files/1c118bfc9afd4ab88f50cf7a8772ebf8a722ca6d#diff-5335907a57d52ad8308fda4946864fbdf9a9c69ee87716d86697a749f72df895).

_Originally posted by @zhumin8 in https://github.com/googleapis/librarian/pull/4381#discussion_r2907389307_
            

Use sentinel errors when appropriate and clean up redundant error messages.

### LINKED ISSUE #4517: java: fix test removed temporarily
This test was failing in ci. temp removal so we can add the ci first.
https://github.com/googleapis/librarian/pull/4516/changes

### PR DESCRIPTION
**Pull request by zhumin8**
Improves error handling in generate.go, use sentinel error for checks in tests. Add back temporary removed test case, and removes a redundant test.

Fix #4517
Fix #4436

### CODE REVIEW

File: internal/librarian/java/generate.go [hunk 1]
```diff
@@ -89,7 +97,7 @@ func generateAPI(ctx context.Context, api *config.API, library *config.Library,
 		return fmt.Errorf("failed to find protos: %w", err)
 	}
 	if len(apiProtos) == 0 {
-		return fmt.Errorf("failed to generate api: no protos found in api %q", api.Path)
+		return ErrNoProtos
```
Comment (noahdietz) [inline internal/librarian/java/generate.go]: ditto re:context/error wrapping
