### PR TITLE
fix(internal/librarian): make response files optional for generate/build

### LINKED ISSUE #1741: librarian: generate error when .librarian/generate-response.json is missing
# Expected

The presence of `.librarian/generate-response.json` at the conclusion of `generate` execution should be **optional**.

# Actual

```sh
chrisdsmith@chrisdsmith:~/oss/librarian$ ./run-librarian-integration-test.sh
Using googleapis source from /usr/local/google/home/chrisdsmith/oss/googleapis
--- Git Reset Summary ---
HEAD is now at c559f93cdc rm .librarian/generate-response.json
Removing .librarian/generator-input/
~/oss/librarian
Running librarian...
2025/08/14 18:45:42 INFO librarian arguments="[generate --image=gcr.io/cloud-devrel-public-resources/librarian-go:infrastructure-public-image-latest --repo=/usr/local/google/home/chrisdsmith/oss/google-cloud-go-2 --library=secretmanager --api=google/cloud/secretmanager/v1,google/cloud/secretmanager/v1beta2 --api-source=/usr/local/google/home/chrisdsmith/oss/googleapis]"
2025/08/14 18:45:43 INFO Temporary working directory dir=/tmp/librarian-20250814T184543Z
2025/08/14 18:45:43 INFO Opening repository dir=/usr/local/google/home/chrisdsmith/oss/googleapis
2025/08/14 18:45:44 INFO Opening repository dir=/usr/local/google/home/chrisdsmith/oss/google-cloud-go-2
2025/08/14 18:45:51 INFO Code will be generated dir=/tmp/librarian-20250814T184543Z/output
2025/08/14 18:45:51 INFO Performing generation for library id=secretmanager
2025/08/14 18:45:51 INFO === Docker start ===============================================================
2025/08/14 18:45:51 INFO /usr/bin/docker run --rm -v /usr/local/google/home/chrisdsmith/oss/google-cloud-go-2/.librarian:/librarian -v /usr/local/google/home/chrisdsmith/oss/google-cloud-go-2/.librarian/generator-input:/input -v /tmp/librarian-20250814T184543Z/output:/output -v /usr/local/google/home/chrisdsmith/oss/googleapis:/source:ro --user 975507:89939 gcr.io/cloud-devrel-public-resources/librarian-go:infrastructure-public-image-latest generate --librarian=/librarian --input=/input --output=/output --source=/source
2025/08/14 18:45:51 INFO --------------------------------------------------------------------------------
time=2025-08-14T18:45:51.602Z level=INFO msg="librariangen: invoked" args="[/usr/local/bin/librariangen generate --librarian=/librarian --input=/input --output=/output --source=/source]"
time=2025-08-14T18:45:51.603Z level=INFO msg="processing api" service_dir=/source/google/cloud/secretmanager/v1
time=2025-08-14T18:45:51.915Z level=INFO msg="processing api" service_dir=/source/google/cloud/secretmanager/v1beta2
time=2025-08-14T18:46:02.608Z level=INFO msg="librariangen: finished successfully"
2025/08/14 18:46:04 INFO === Docker end =================================================================
2025/08/14 18:46:04 WARN fail to remove file name=/usr/local/google/home/chrisdsmith/oss/google-cloud-go-2/.librarian/generate-response.json err="remove /usr/local/google/home/chrisdsmith/oss/google-cloud-go-2/.librarian/generate-response.json: no such file or directory"
2025/08/14 18:46:04 failed to read response file, path: /usr/local/google/home/chrisdsmith/oss/google-cloud-go-2/.librarian/generate-response.json, error: open /usr/local/google/home/chrisdsmith/oss/google-cloud-go-2/.librarian/generate-response.json: no such file or directory
exit status 1
```

### PR DESCRIPTION
**Pull request by jskeet**
readLibraryState() now returns a nil pointer (but no error) if the container response file doesn't exist. When the response is required (e.g. for configure) this should be checked explicitly.

Fixes #1741

### CODE REVIEW

File: internal/librarian/generate.go [hunk 1]
```diff
@@ -506,6 +506,9 @@ func (r *generateRunner) runConfigureCommand(ctx context.Context) (string, error
 	if err != nil {
 		return "", err
 	}
+	if libraryState == nil {
+		return "", fmt.Errorf("no response file for configure container command")
```
Comment (chingor13) [inline internal/librarian/generate.go:510]:
```suggestion
		return "", fmt.Errorf("no response file for generate container command")
```

**Review by chingor13 — APPROVED** [review]

File: internal/librarian/generate.go (hunk 1 above)
Comment (jskeet) [reply internal/librarian/generate.go:510]: This is within `runConfigureCommand` - it would be the generate *CLI* command, but it's the configure *container* command.

File: internal/librarian/state.go [hunk 2]
```diff
@@ -158,17 +158,24 @@ func saveLibrarianState(repoDir string, state *config.LibrarianState) error {
...
-		if err := os.Remove(jsonFilePath); err != nil {
+		if err := os.Remove(jsonFilePath); err != nil && !errors.Is(err, os.ErrNotExist) {
 			slog.Warn("fail to remove file", slog.String("name", jsonFilePath), slog.Any("err", err))
 		}
 	}()
 	if err != nil {
+		// If we only failed to read the file because it didn't exist, just succeed
+		// with a nil pointer.
+
+		if errors.Is(err, os.ErrNotExist) {
```
Comment (JoeWang1127) [inline internal/librarian/state.go:176]: I think it's better we check the stat of the file and returns early if it doesn't exist.

Comment (jskeet) [reply internal/librarian/state.go:176]: I did wonder about that... @codyoss do you have a preference here?

File: internal/librarian/generate_test.go [hunk 3]
```diff
@@ -143,7 +162,8 @@ func TestRunBuildCommand(t *testing.T) {
 			container: &mockContainerClient{
 				noBuildResponse: true,
 			},
-			wantErr: true,
+			wantErr:        false,
```
[the remark this answers is not in the document]
Comment (jskeet) [reply internal/librarian/generate_test.go:165]: Done.

File: internal/librarian/state.go (hunk 2 above)
Comment (jskeet) [reply internal/librarian/state.go:176]: Ping @codyoss for a decision on this? (Would really like to get this PR in, as it will stop Go generation from failing post-container.)

Comment (codyoss) [reply internal/librarian/state.go:176]: I am no preference. I think what is here is fine.

Comment (jskeet) [reply internal/librarian/state.go:176]: Having chatted with Cody, I'll keep this as it is. Even if if we were to use Stat, we'd still be catching an error.

**Review by codyoss — APPROVED** [review]
