### PR TITLE
fix: enforce removal before copying library files

### LINKED ISSUE #2593: librarian: file copying doesn't enforce previous file removal
When copying generated files (as opposed to updated files for versions etc) we should fail if the file already exists in the destination - because it means our removal regexes aren't removing everything they should.

At the moment, this doesn't happen. The file is just truncated, due to the use of `os.Create` (in command.go, `copyFile`). I can't immediately see a similar function that implements "create, failing if the file already exists". We could try to open the file first to see if it exists.

(In Librarian v0.1.0 we implemented this by simply using `os.CopyFS` for the whole output directory. I suspect that wouldn't work with symlinks though.)

Assigning to Cody to validate that this is a bug and consider the priority. Note that we'll need to work out when to require this and when not to - it's *probably* only in generate and maybe configure that this should happen.

### PR DESCRIPTION
**Pull request by JoeWang1127**
Fixes #2593

### CODE REVIEW

File: internal/librarian/command.go [hunk 1]
```diff
@@ -299,15 +299,21 @@ func cleanAndCopyLibrary(state *config.LibrarianState, repoDir, libraryID, outpu
...
+// If `failOnExistingFile` is true, the function will check if a file already
+// exists at the destination. If it does, an error is returned immediately without copying.
+// If `failOnExistingFile` is false, it will overwrite any existing files.
+//
 // If there's no files in the library's SourceRoots under the src directory, no copy will happen.
+//
 // If a file is being copied to the library's SourceRoots in the dest folder but the folder does
 // not exist, the copy fails.
-func copyLibraryFiles(state *config.LibrarianState, dest, libraryID, src string) error {
+func copyLibraryFiles(state *config.LibrarianState, dest, libraryID, src string, failOnExistingFile bool) error {
```
Comment (miguelvelezsa) [inline internal/librarian/command.go]: WDYT about using overwrite or overwriteFile instead of failOnExistingFile?

File: internal/librarian/generate_command.go [hunk 2]
```diff
@@ -375,7 +375,7 @@ func (r *generateRunner) runConfigureCommand(ctx context.Context, outputDir stri
 		r.state.Libraries[i] = libraryState
 	}
 
-	if err := copyLibraryFiles(r.state, r.repo.GetDir(), libraryState.ID, outputDir); err != nil {
+	if err := copyLibraryFiles(r.state, r.repo.GetDir(), libraryState.ID, outputDir, false); err != nil {
```
Comment (miguelvelezsa) [inline internal/librarian/generate_command.go]: is there a test checking this?
