### PR TITLE
fix(internal/librarian/java): move generate to pom per library

### LINKED ISSUE #4493: java: refactor and reduce calls to serviceconfig.Find
Java generate and postprocess currently calls `serviceconfig.Find` 4 times.

### LINKED ISSUE #5015: java: move pom generation logic outside of per api generate
`generatePomsIfMissing` generate pom.xml for grpc- and proto-, these can be per API, but also generates client, bom and parent pom what are per library. Need to move logic outside of per api generate to avoid duplications.

example dir structure for secretmanager
```
├── google-cloud-secretmanager
│   └── pom.xml
├── google-cloud-secretmanager-bom
│   └── pom.xml
├── grpc-google-cloud-secretmanager-v1
│   └── pom.xml
├── grpc-google-cloud-secretmanager-v1beta1
│   └── pom.xml
├── grpc-google-cloud-secretmanager-v1beta2
│   └── pom.xml
├── pom.xml
├── proto-google-cloud-secretmanager-v1
│   └── pom.xml
├── proto-google-cloud-secretmanager-v1beta1
│   └── pom.xml
├── proto-google-cloud-secretmanager-v1beta2
│   └── pom.xml
├── README.md
└── samples
```

### PR DESCRIPTION
**Pull request by zhumin8**
Move generate pom logic outside of generateAPI, it should only be generated once per library, instead of per API.

Fix #5015
Fix #4493

### CODE REVIEW

File: internal/librarian/java/generate_test.go [hunk 1]
```diff
@@ -525,20 +534,102 @@ func TestGenerateLibrary_Error(t *testing.T) {
...
+				}
+				if err := os.WriteFile(filepath.Join(library.Output, "owlbot.py"), []byte("#!/usr/bin/env python3\npass"), 0755); err != nil {
+					t.Fatal(err)
+				}
+				templatesDir := filepath.Join(filepath.Dir(library.Output), owlbotTemplatesRelPath)
+				if err := os.MkdirAll(templatesDir, 0755); err != nil {
+					t.Fatal(err)
+				}
+			},
+			wantErr: errors.New("failed to find monorepo version"),
```
Comment (JoeWang1127) [inline internal/librarian/java/generate_test.go]: Create an error.

File: internal/librarian/java/generate_test.go [hunk 2]
```diff
@@ -525,20 +534,102 @@ func TestGenerateLibrary_Error(t *testing.T) {
...
 				test.setup(t, test.library)
 			}
-			cfg := &config.Config{Language: "java"}
+			cfg := &config.Config{
+				Language:  config.LanguageJava,
+				Libraries: []*config.Library{test.library},
+			}
 			err := Generate(t.Context(), cfg, test.library, &sources.Sources{Googleapis: googleapisDir})
-			if !errors.Is(err, test.wantErr) {
+			if err == nil || !strings.Contains(err.Error(), test.wantErr.Error()) {
```
Comment (JoeWang1127) [inline internal/librarian/java/generate_test.go]: nit: refactor to check the error, not the error message.

File: internal/librarian/java/generate.go [hunk 3]
```diff
@@ -65,16 +65,39 @@ func Generate(ctx context.Context, cfg *config.Config, library *config.Library,
...
 		return fmt.Errorf("failed to generate .repo-metadata.json: %w", err)
 	}
+
+	apiConfigs := make(map[string]*serviceconfig.API)
+	for _, api := range library.APIs {
+		apiCfg, err := serviceconfig.Find(googleapisDir, api.Path, config.LanguageJava)
+		if err != nil {
+			return fmt.Errorf("failed to find api config for %s: %w", api.Path, err)
+		}
+		apiConfigs[api.Path] = apiCfg
```
[the remark this answers is not in the document]
Comment (zhumin8) [reply internal/librarian/java/generate.go]: done.

File: internal/librarian/java/generate_test.go (hunk 2 above)
Comment (zhumin8) [reply internal/librarian/java/generate_test.go]: oops, missed this one. Done.

File: internal/librarian/java/pom_test.go [hunk 4]
```diff
@@ -111,10 +113,11 @@ func TestCollectModules_Error(t *testing.T) {
 					{Path: "google/ads/unrecognized/v1"},
 				},
 			},
+			transports: map[string]serviceconfig.Transport{},
 		},
 	} {
 		t.Run(test.name, func(t *testing.T) {
-			if _, err := collectModules(test.library, t.TempDir(), "/nonexistent", "1.2.3", &repoMetadata{}); err == nil {
+			if _, err := collectModules(test.library, t.TempDir(), "1.2.3", &repoMetadata{}, test.transports); err == nil {
```
[the remark this answers is not in the document]
Comment (zhumin8) [reply internal/librarian/java/pom_test.go]: Will do in followups - #5023

**Review by JoeWang1127 — APPROVED** [review]
