### PR TITLE
test: add integration build tag

### LINKED ISSUE #2720: all: TestFindLatestImage fails at HEAD when running go test ./...
`TestFindLatestImage` fails when running `go test ./...` on a fresh clone of https://github.com/googleapis/librarian with the following errors:

```
--- FAIL: TestFindLatestImage (0.00s)
    --- FAIL: TestFindLatestImage/AR_pinned (0.34s)
        system_test.go:493: FindLatestImage() error = rpc error: code = PermissionDenied desc = Permission 'artifactregistry.versions.list' denied on resource '//artifactregistry.googleapis.com/projects/cloud-sdk-librarian-prod/locations/us-central1/repositories/images-prod/packages/librarian-go' (or it may not exist).
            error details: name = ErrorInfo reason = IAM_PERMISSION_DENIED domain = artifactregistry.googleapis.com metadata = map[permission:artifactregistry.versions.list resource:projects/cloud-sdk-librarian-prod/locations/us-central1/repositories/images-prod/packages/librarian-go]
    --- FAIL: TestFindLatestImage/AR_unpinned (0.38s)
        system_test.go:493: FindLatestImage() error = rpc error: code = PermissionDenied desc = Permission 'artifactregistry.versions.list' denied on resource '//artifactregistry.googleapis.com/projects/cloud-sdk-librarian-prod/locations/us-central1/repositories/images-prod/packages/librarian-go' (or it may not exist).
            error details: name = ErrorInfo reason = IAM_PERMISSION_DENIED domain = artifactregistry.googleapis.com metadata = map[permission:artifactregistry.versions.list resource:projects/cloud-sdk-librarian-prod/locations/us-central1/repositories/images-prod/packages/librarian-go]
2025/10/29 23:06:28 INFO Checking for repository dir=/var/folders/_j/n7nk6w3x6t3f0xjc0nz2chr80000gn/T/TestGitCheckoutknown_SHA260199818/001/librarian
2025/10/29 23:06:28 INFO Checking for repository dir=/var/folders/_j/n7nk6w3x6t3f0xjc0nz2chr80000gn/T/TestGitCheckoutunknown_SHA3275039683/001/librarian
2025/10/29 23:06:28 INFO Repository not found, executing clone
...
```

### PR DESCRIPTION
**Pull request by zhumin8**
This test verify the integration of the librarian tool with external systems, GitHub and Artifact Registry. It has expectation setups in env vars and auth to properly work.
With an `integration` build tag, all tests in system_test.go will be skipped when running `go test ./...` locally. Which is same behavior for most developers who does not have relevant env vars setup.

Also remove the temp skip for TestFindLatestImage because it is no longer triggered with standard `go test ./...`. Added a note to make debugging easier.

Fixes #2720

### CODE REVIEW

File: system_test.go [hunk 1]
```diff
@@ -12,6 +12,8 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
```
Comment (ldetmer) [inline system_test.go]: I see your comment in the ticket.  Is it just checking if credentials are null? I actually think we would prefer to do that.  Similar to checking if [protoc is installed here](https://github.com/googleapis/librarian/blob/fb8c5574f53f612395727b2c4e19df470c2ea1e6/internal/sidekick/sidekick_test.go#L45), we would check if credentials exist.  Is there a security concern?

**Review by ldetmer — APPROVED** [review]
