### PR TITLE
fix(internal/librarian): dedupe release note entries

### LINKED ISSUE #549: librarian: dedupe commit messages in release notes
If we see the same conventional commit line in multiple commits that contribute to a single library (e.g. separately for v1 and v1beta) we should only create a single entry for that commit line in the release notes.

It should be straighforward to just keep a set of "lines we've already included".

### PR DESCRIPTION
**Pull request by chingor13**
Fixes #549

### CODE REVIEW

File: internal/librarian/createreleasepr.go [hunk 1]
```diff
@@ -308,24 +310,29 @@ func generateReleaseCommitForEachLibrary(state *commandState, inputDirectory str
...
+			fixes[fix] = true
+		}
 	}
 
 	var builder strings.Builder
 
-	maybeAppendReleaseNotesSection(&builder, "New features", features)
-	maybeAppendReleaseNotesSection(&builder, "Bug fixes", fixes)
-	maybeAppendReleaseNotesSection(&builder, "Documentation improvements", docs)
+	maybeAppendReleaseNotesSection(&builder, "New features", slices.Collect(maps.Keys(features)))
```
Comment (jba) [inline internal/librarian/createreleasepr.go:333]: Sort for determinism.
Or if order matters, you need to use a slice, and use a map only to dedup.

**Review by julieqiu — APPROVED** [review]

File: internal/librarian/createreleasepr.go (hunk 1 above)
Comment (chingor13) [reply internal/librarian/createreleasepr.go]: Rewrote to preserve the initial ordering (we use the map to only decide if we have seen the entry before)

Added a TODO linking to https://github.com/googleapis/librarian/issues/564

File: internal/librarian/createreleasepr.go [hunk 2]
```diff
@@ -307,18 +307,37 @@ func generateReleaseCommitForEachLibrary(state *commandState, inputDirectory str
...
 
+// TODO(https://github.com/googleapis/librarian/issues/564): decide on release notes ordering
 func formatReleaseNotes(commitMessages []*CommitMessage) string {
+	// Group release notes by type, preserving ordering (FIFO)
 	features := []string{}
+	featuresSeen := make(map[string]bool)
 	docs := []string{}
+	docsSeen := make(map[string]bool)
 	fixes := []string{}
+	fixesSeen := make(map[string]bool)
```
Comment (julieqiu) [inline internal/librarian/createreleasepr.go:318]: nit:

```
var features, docs, fixes []string
```

**Review by julieqiu — APPROVED** [review]

File: internal/librarian/createreleasepr.go (hunk 2 above)
Comment (chingor13) [reply internal/librarian/createreleasepr.go:316]: Done.

**Review by julieqiu — APPROVED** [review]

File: internal/librarian/createreleasepr.go [hunk 3]
```diff
@@ -307,18 +307,35 @@ func generateReleaseCommitForEachLibrary(state *commandState, inputDirectory str
...
 
-	// TODO(https://github.com/googleapis/librarian/issues/549): deduping (same message across multiple commits)
 	// TODO(https://github.com/googleapis/librarian/issues/547): perhaps record breaking changes in a separate section
 	// TODO(https://github.com/googleapis/librarian/issues/550): include backlinks, googleapis commits etc
 	for _, commitMessage := range commitMessages {
-		features = append(features, commitMessage.Features...)
-		docs = append(docs, commitMessage.Docs...)
-		fixes = append(fixes, commitMessage.Fixes...)
+		for _, feature := range commitMessage.Features {
```
Comment (jba) [inline internal/librarian/createreleasepr.go:321]: These are all the same, so this could be written
```
dedup := func(s []string) []string {
    seen := make(map[string]bool)
    var r []string
    for _, el := range s {
      if !seen[el] {.....}
   }
   return r
}

features := dedup(commitMessage.Features)
...
...
```

Comment (chingor13) [reply internal/librarian/createreleasepr.go:321]: Filed https://github.com/googleapis/librarian/issues/600 to consider following up on this
