### PR TITLE
fix(internal/librarian): run tidy generate in runCreate

### LINKED ISSUE #3390: librarian: run tidy at the end of create
When librarian create finishes, we should run tidy to ensure that the new librarian.yaml is tidy.

### PR DESCRIPTION
**Pull request by zhumin8**
Run tidy after generate in create command. 
An alternative is to run tidy after `addLibraryToLibrarianConfig` and before `runGenerate`. However, benefit to run tidy after generate is that if librarian.yaml read in is not in a clean state, it will by tidy after run.

Fix #3390

### CODE REVIEW

File: internal/librarian/create_test.go [hunk 1]
```diff
@@ -18,104 +18,152 @@ import (
...
+
+			if diff := cmp.Diff(test.wantFinalLibraries, gotCfg.Libraries); diff != "" {
+				t.Errorf("final libraries mismatch (-want +got):\n%s", diff)
 			}
 
-			readmePath := filepath.Join(test.wantOutput, "README.md")
+			readmePath := filepath.Join(test.wantGeneratedOutputDir, "README.md")
 			if _, err := os.Stat(readmePath); err != nil {
 				t.Errorf("expected README.md at %s: %v", readmePath, err)
 			}
```
[the remark this answers is not in the document]
Comment (zhumin8) [reply internal/librarian/create_test.go]: fixed.

**Review by ldetmer — APPROVED** [review]

File: internal/librarian/create_test.go [hunk 2]
```diff
@@ -18,104 +18,158 @@ import (
...
-			want := "0.0.0"
+			const want = "0.0.0"
 			if diff := cmp.Diff(want, string(content)); diff != "" {
 				t.Errorf("VERSION mismatch (-want +got):\n%s", diff)
 			}
 		})
 	}
 }
 
+func createServiceConfig(t *testing.T, tmpDir, name string) {
```
Comment (julieqiu) [inline internal/librarian/create_test.go]: Instead of creating a new file, can internal/testdata/googleapis be used?

File: internal/librarian/create.go [hunk 3]
```diff
@@ -80,14 +80,39 @@ func runCreate(ctx context.Context, name, output string, channel ...string) erro
...
+			return err
+		}
 	default:
 		return errUnsupportedLanguage
 	}
+	return yaml.Write(librarianConfigPath, formatConfig(cfg))
+}
+
+func runGenerateAndTidy(ctx context.Context, cfg *config.Config, all bool, libraryName string) error {
+	if err := runGenerate(ctx, all, libraryName); err != nil {
```
Comment (julieqiu) [inline internal/librarian/create.go]: runGenerate also run yaml.Read, and it calls generateLibrary which calls `fetchSource`. Can we pass `cfg` and `fetchSource` in as well?

Feel free to do as a follow up

Comment (zhumin8) [reply internal/librarian/create.go]: raised https://github.com/googleapis/librarian/issues/3463 to track the follow up.
