### PR TITLE
fix(internal/librarian/java): respect distribution override and unify coordinate logic

### LINKED ISSUE #5048: java: client module artifactId special cases should derive from distribution override
The logic that derives module names from library name works common cases, but there are 43 irregular ones that do not follow this pattern.
https://github.com/googleapis/librarian/blob/f2af8417592b22abd1f12dce7ba54c535dfecec5/internal/librarian/java/postprocess.go#L135-L142

When distribution override is present, need to add logic to use artifact id from it instead.

### PR DESCRIPTION
**Pull request by zhumin8**
The module derivation logic is updated to prioritize the artifact ID from distribution_name_override when present. This ensures that restructuring and POM generation use the correct paths.

Also refactored to centralize coordinate management and remove repeating logic. The javaModules struct is  extended to use full coordinate objects for all module types.

Fix #5048

### CODE REVIEW

File: internal/librarian/java/pom.go [hunk 1]
```diff
@@ -179,15 +179,14 @@ func detectIndentation(content string, index int) string {
 // module's POM requires a full list of all proto and gRPC dependencies
 // to ensure its dependency list is fully synchronized.
 func collectModules(library *config.Library, libraryDir, monorepoVersion string, metadata *repoMetadata, transports map[string]serviceconfig.Transport) ([]javaModule, error) {
```
Comment (JoeWang1127) [inline internal/librarian/java/pom.go]: nit: create a struct for the inputs.
