### PR TITLE
fix: handle multi-line commit message

### LINKED ISSUE #2234: librarian: cater for wrapped nested commits
There appear to be visual line breaks when I click the squash and merge button on the librarian generate PR  https://github.com/googleapis/google-cloud-python/pull/14470. There may not actually be line breaks but it appears in the screenshot below. If you recall, we saw erroneous line breaks when we merged the last librarian generate PR. See https://github.com/googleapis/google-cloud-python/commit/09f78e3ca85671594e20c3182038238e58d3d8cb

In the librarian PR description, I see the following
```
BEGIN_NESTED_COMMIT
feat: [google-cloud-video-live-stream] Added StartDistribution/StopDistribution methods and Distribution/DistributionStream messages used for distributing live streams to external RTMP/SRT endpoints

PiperOrigin-RevId: 808091810

Source-link: [googleapis/googleapis@c4e80cd](https://github.com/googleapis/googleapis/commit/c4e80cd2d3321cc37cf1c3713bb02529857728d1)
END_NESTED_COMMIT
```

Image

However when I click `squash and merge`, I see

```
BEGIN_NESTED_COMMIT
feat: [google-cloud-video-live-stream] Added
StartDistribution/StopDistribution methods and
Distribution/DistributionStream messages used for distributing live
streams to external RTMP/SRT endpoints


PiperOrigin-RevId: 808091810

Source-link:
[googleapis/googleapis@c4e80cd](https://github.com/googleapis/googleapis/commit/c4e80cd2d3321cc37cf1c3713bb02529857728d1)
END_NESTED_COMMIT
```

Image

### PR DESCRIPTION
**Pull request by JoeWang1127**
Fixes #2234

### CODE REVIEW

File: internal/conventionalcommits/conventional_commits_test.go [hunk 1]
```diff
@@ -453,6 +453,57 @@ END_COMMIT_OVERRIDE`,
 				},
 			},
 		},
+		{
+			name: "parse_multiple_lines_message_inside_nested_commit_multi_line_headers",
```
Comment (JoeWang1127) [inline internal/conventionalcommits/conventional_commits_test.go:457]: Underscore is preferred over whitespace in test names: https://g3doc.corp.google.com/company/teams/go-community/gotip/episodes/117.md?cl=head

File: internal/conventionalcommits/conventional_commits.go [hunk 2]
```diff
@@ -190,17 +190,25 @@ func parseSimpleCommit(commitPart commitPart, commit *gitrepo.Commit, libraryID
...
-	// will be discarded.
+	// Hold the subjects of each commit.
+	var subjects [][]string
+	// If the body lines have multiple headers, separate them into different conventional commit, all associated with
+	// the same commit sha.
 	for _, bodyLine := range bodyLines {
 		header, ok := parseHeader(bodyLine)
 		if !ok {
 			slog.Warn("bodyLine is not a header", "bodyLine", bodyLine, "hash", commit.Hash.String())
+			if len(commits) == 0 {
```
Comment (suztomo) [inline internal/conventionalcommits/conventional_commits.go:201]: I feel it's natural to check the length of subjects because the next sentence is to access `subjects[len(subjects)-1]`.

**Review by ldetmer — APPROVED** [review]

File: internal/conventionalcommits/conventional_commits.go (hunk 2 above)
Comment (JoeWang1127) [reply internal/conventionalcommits/conventional_commits.go:201]: The the length of commits and subjects are always the same.
