### PR TITLE
fix(internal/librarian): Remove publish-release-artifacts command

### LINKED ISSUE #780: librarian: remove publish-release-artifacts command
Reference: go/librarian:cli-reimagined

Remove this command and associated code only referenced by it. We may add this back in the future when we take a closer look at releasing. For now let's simplify the codebase.

### PR DESCRIPTION
**Pull request by K-Kumar-01**
Remove `publish-release-artifacts` command, associated code and documentation.

Closes #780

### CODE REVIEW

**Comment by K-Kumar-01** [comment]
@zhumin8 
PTAL

**Comment by zhumin8** [comment]
please fix test failures: 
`Error:         internal/librarian/command.go:200:6: func formatReleaseTag is unused (unused)`

File: internal/config/config.go [hunk 1]
```diff
@@ -52,6 +52,15 @@ type Config struct {
...
 	ArtifactRoot string
+	// Source is the path to the root of the googleapis repository.
+	// When this is not specified, the googleapis repository is cloned
+	// automatically.
+	//
+	// Source is used by generate, update-apis, update-image-tag and configure
+	// commands.
+	//
+	// Source is specified with the -source flag.
+	Source string
```
Comment (codyoss) [inline internal/config/config.go:63]: This might be from a bad merge? This field already exists below.

Comment (K-Kumar-01) [reply internal/config/config.go]: @codyoss 
Apologies for the bad merge. I have fixed it.
