### PR TITLE
fix(internal): move LIBRARIAN_GITHUB_TOKEN to Config

### LINKED ISSUE #510: librarian: convert LIBRARIAN_GITHUB_TOKEN to flag

### PR DESCRIPTION
**Pull request by dangazineu**
Moved resolution of `LIBRARIAN_GITHUB_TOKEN` environment variable into the `config` package. 

Now `githubrepo.NewClient` takes a GH Access Token as a parameter instead of getting it from the environment, improving testability. Refactored callers of `githubrepo.NewClient` to retrieve that value from the `config.Config`. Also replaced any direct flag access in those functions to use values `Config` instance that is now available.

Fixes #510.

### CODE REVIEW

File: internal/config/config.go [hunk 1]
```diff
@@ -111,5 +115,21 @@ func New() *Config {
...
+// IsValid ensures the values contained in a Config are valid.
+func (c *Config) IsValid() (bool, error) {
+	if err := c.validatePush(); err != nil {
+		return false, err
+	}
+	return true, nil
+}
+
+func (c *Config) validatePush() error {
+	if c.Push && c.GitHubToken == "" {
```
Comment (julieqiu) [inline internal/config/config.go:131]: I would move this inside `IsValid` since it's just one line to avoid a level of indirection (unless there's a reason for separating that I might not be seeing)

File: internal/librarian/configure.go [hunk 2]
```diff
@@ -99,17 +100,19 @@ func init() {
 }
 
 func runConfigure(ctx context.Context) error {
+	cfg := config.New()
```
Comment (julieqiu) [inline internal/librarian/configure.go:103]: Leaving a comment for me to remember to factor this out into internal/cli

**Review by julieqiu — CHANGES_REQUESTED** [review]

File: internal/config/config.go (hunk 1 above)
Comment (dangazineu) [reply internal/config/config.go:124]: I imagine `IsValid()` will grow to include many other validations, so separating them by "theme" would make sense. For now though, I agree that the additional method only serves as extra indirection, removed.

**Review by julieqiu — APPROVED** [review]
