### PR TITLE
fix(internal/librarian): read configure response

### LINKED ISSUE #985: librarian: change librarian state after configuring a library and write it back to `state.yaml`

### PR DESCRIPTION
**Pull request by JoeWang1127**
Fixes #985

### CODE REVIEW

File: internal/docker/docker.go [hunk 1]
```diff
@@ -301,3 +334,47 @@ func writeRequest(state *config.LibrarianState, libraryID, jsonFilePath string)
 
 	return nil
 }
+
+// readResponse reads the library state from configure-response.json.
+//
+// The response file is removed afterwards.
+func readResponse(contentLoader func(data []byte, state *config.LibraryState) error, jsonFilePath string) (*config.LibraryState, error) {
```
Comment (zhumin8) [inline internal/docker/docker.go:341]: Can `readResponse` and `writeLibrarianState` move to state.go to centralize operations on state.yaml and state struct?

File: internal/docker/docker_test.go [hunk 2]
```diff
@@ -251,7 +253,85 @@ func TestDockerRun(t *testing.T) {
...
+				string(CommandConfigure),
+				"--librarian=/librarian",
+				"--input=/input",
+				"--source=/source",
+				fmt.Sprintf("--library-id=%s", testLibraryID),
+			},
+			wantErr: false,
+		},
+		{
+			name: "Configure with multiple libraries",
```
Comment (zhumin8) [inline internal/docker/docker_test.go:279]: I wonder if it is a valid case to configure multiple libraries?

File: internal/docker/docker.go [hunk 3]
```diff
@@ -301,3 +334,47 @@ func writeRequest(state *config.LibrarianState, libraryID, jsonFilePath string)
...
+		}
+	}(jsonFilePath)
+	if err != nil {
+		return nil, fmt.Errorf("failed to read response JSON file: %w", err)
+	}
+
+	libraryState := &config.LibraryState{}
+
+	if err := contentLoader(data, libraryState); err != nil {
+		return nil, fmt.Errorf("failed to unmarshal JSON to state: %w", err)
```
Comment (zhumin8) [inline internal/docker/docker.go:356]: Can we be more specific on this error? It may be helpful for debug if for example  file path is included in the error

**Review by zhumin8 — COMMENTED** [review]
Looks good in general. A few small comments.

File: internal/docker/docker.go (hunk 3 above)
Comment (JoeWang1127) [reply internal/docker/docker.go]: Done.

File: go.mod [hunk 4]
```diff
@@ -10,6 +10,7 @@ require (
 	github.com/google/go-cmp v0.7.0
 	github.com/google/go-github/v69 v69.2.0
 	github.com/googleapis/gax-go/v2 v2.14.2
+	github.com/stretchr/testify v1.10.0
```
Comment (jba) [inline go.mod:13]: Don't use this package, or any test helper package.

File: internal/config/config.go [hunk 5]
```diff
@@ -28,14 +28,18 @@ const (
 	BuildRequest string = "build-request.json"
 	// ConfigureRequest is a JSON file that describes which library to configure.
 	ConfigureRequest string = "configure-request.json"
+	// ConfigureResponse is a JSON file that describes which library to change
+	// after initial configuration.
+	ConfigureResponse string = "configure-response.json"
```
Comment (jba) [inline internal/config/config.go:33]: You can omit "string" here, and for all of these consts.

File: go.mod (hunk 4 above)
Comment (jba) [reply go.mod:13]: https://go.dev/wiki/TestComments#assert-libraries

File: internal/docker/docker.go [hunk 6]
```diff
@@ -301,3 +334,47 @@ func writeRequest(state *config.LibrarianState, libraryID, jsonFilePath string)
...
+		}
+	}(jsonFilePath)
+	if err != nil {
+		return nil, fmt.Errorf("failed to read response JSON file: %w", err)
+	}
+
+	libraryState := &config.LibraryState{}
+
+	if err := contentLoader(data, libraryState); err != nil {
+		return nil, fmt.Errorf("failed to unmarshal JSON file, %s, to state: %w", jsonFilePath, err)
```
Comment (jba) [inline internal/docker/docker.go:356]: This function doesn't know it's JSON, that's why it takes a contentLoader.
If you know it's JSON, remove contentLoader.

File: internal/docker/docker.go [hunk 7]
```diff
@@ -301,3 +334,47 @@ func writeRequest(state *config.LibrarianState, libraryID, jsonFilePath string)
...
+	}
+
+	return libraryState, nil
+}
+
+// writeLibrarianState writes the given librarian state to a yaml file.
+func writeLibrarianState(contentParser func(state *config.LibrarianState) ([]byte, error), state *config.LibrarianState, yamlFilePath string) error {
+	yamlFile, err := os.Create(yamlFilePath)
+	if err != nil {
+		return fmt.Errorf("failed to create librarian state file: %w", err)
```
Comment (jba) [inline internal/docker/docker.go:366]: include filename

Comment (jba) [reply internal/docker/docker.go:366]: also below

File: internal/docker/docker_test.go [hunk 8]
```diff
@@ -251,7 +253,85 @@ func TestDockerRun(t *testing.T) {
 					RepoDir:   "absolute/path/to/repo",
 					ApiRoot:   testAPIRoot,
 				}
-				return d.Configure(ctx, configureRequest)
+				jsonData, _ := json.MarshalIndent(&config.LibraryState{}, "", "  ")
+				jsonFilePath := filepath.Join(configureRequest.RepoDir, config.LibrarianDir, config.ConfigureResponse)
+				os.WriteFile(jsonFilePath, jsonData, 0644)
+				_, err := d.Configure(ctx, configureRequest)
+				defer os.RemoveAll(configureRequest.RepoDir)
```
Comment (jba) [inline internal/docker/docker_test.go:260]: This should go higher up, not sure exactly where, but definitely not just before you return an error.
(If you want to do this here, just do it, don't defer it.)

File: internal/docker/docker_test.go [hunk 9]
```diff
@@ -251,7 +253,85 @@ func TestDockerRun(t *testing.T) {
...
+				jsonData, _ := json.MarshalIndent(&config.LibraryState{
+					ID: testLibraryID,
+					APIs: []*config.API{
+						{
+							Path:          "example/path/v1",
+							ServiceConfig: "generated_example_v1.yaml",
+						},
+					},
+				}, "", "  ")
+				os.MkdirAll(filepath.Join(configureRequest.RepoDir, config.LibrarianDir), 0755)
```
Comment (jba) [inline internal/docker/docker_test.go:325]: Check all errors, here and below.

File: internal/docker/docker_test.go [hunk 10]
```diff
@@ -438,3 +551,213 @@ func TestToGenerateRequestJSON(t *testing.T) {
 		})
 	}
 }
+
+func TestReadResponseJson(t *testing.T) {
```
Comment (jba) [inline internal/docker/docker_test.go:555]: JSON

File: internal/docker/docker_test.go [hunk 11]
```diff
@@ -438,3 +551,213 @@ func TestToGenerateRequestJSON(t *testing.T) {
...
+		t.Run(test.name, func(t *testing.T) {
+			tempDir := t.TempDir()
+			if test.name == "invalid_file_name" {
+				filePath := filepath.Join(tempDir, "my\x00file.json")
+				_, err := readResponse(contentLoader, filePath)
+				if err == nil {
+					t.Errorf("readResponse() expected an error but got nil")
+				}
+
+				assert.Contains(t, err.Error(), "failed to read response JSON file")
```
Comment (jba) [inline internal/docker/docker_test.go:607]: Rewrite all these asserts as ordinary Go code. You can avoid duplication like so:
```
if g, w := err.Error(), "failed to..."; !strings.Contains(g, w) {
   t.Errorf("got %q, wanted it to contain %q", g, w)
}
```

File: internal/docker/docker_test.go [hunk 12]
```diff
@@ -438,3 +551,213 @@ func TestToGenerateRequestJSON(t *testing.T) {
...
+			}
+
+			if diff := cmp.Diff(string(wantBytes), string(gotBytes)); diff != "" {
+				t.Errorf("Generated YAML mismatch (-want +got):\n%s", diff)
+			}
+		})
+	}
+}
+
+func copyFile(src, dst string) {
```
Comment (jba) [inline internal/docker/docker_test.go:757]: should return error
check all errors

**Review by jba — CHANGES_REQUESTED** [review]

File: internal/docker/docker_test.go (hunk 11 above)
Comment (JoeWang1127) [reply internal/docker/docker_test.go:607]: Done.

File: internal/docker/docker_test.go (hunk 9 above)
Comment (JoeWang1127) [reply internal/docker/docker_test.go]: Done.

File: internal/docker/docker_test.go (hunk 10 above)
Comment (JoeWang1127) [reply internal/docker/docker_test.go]: Done.

File: internal/docker/docker_test.go [hunk 13]
```diff
@@ -251,7 +253,85 @@ func TestDockerRun(t *testing.T) {
 					RepoDir:   "absolute/path/to/repo",
 					ApiRoot:   testAPIRoot,
 				}
-				return d.Configure(ctx, configureRequest)
+				jsonData, _ := json.MarshalIndent(&config.LibraryState{}, "", "  ")
+				jsonFilePath := filepath.Join(configureRequest.RepoDir, config.LibrarianDir, config.ConfigureResponse)
+				os.WriteFile(jsonFilePath, jsonData, 0644)
```
[the remark this answers is not in the document]
Comment (JoeWang1127) [reply internal/docker/docker_test.go]: Done.

File: go.mod (hunk 4 above)
Comment (JoeWang1127) [reply go.mod]: Done.

File: internal/docker/docker_test.go (hunk 12 above)
Comment (JoeWang1127) [reply internal/docker/docker_test.go]: Done.

File: internal/docker/docker.go (hunk 6 above)
Comment (JoeWang1127) [reply internal/docker/docker.go]: I changed the error message.

File: internal/docker/docker_test.go [hunk 14]
```diff
@@ -754,10 +820,20 @@ func TestWriteLibrarianState(t *testing.T) {
...
+	if err != nil {
+		return err
+	}
 	defer sourceFile.Close()
-	destinationFile, _ := os.Create(dst)
+	destinationFile, err := os.Create(dst)
+	if err != nil {
+		return err
+	}
 	defer destinationFile.Close()
```
[the remark this answers is not in the document]
Comment (JoeWang1127) [reply internal/docker/docker_test.go]: Done.

File: internal/docker/docker.go (hunk 1 above)
Comment (JoeWang1127) [reply internal/docker/docker.go]: I discussed a similar issue with Cody in https://github.com/googleapis/librarian/pull/1017/files#r2240554391, I decided to move these functions to `state.go`.

File: internal/config/state.go [hunk 15]
```diff
@@ -218,3 +220,47 @@ func isValidImage(image string) bool {
...
 	return ref != "" && tag != ""
 }
+
+// ReadResponse reads the library state from configure-response.json.
+//
+// The response file is removed afterwards.
+func ReadResponse(contentLoader func(data []byte, state *LibraryState) error, jsonFilePath string) (*LibraryState, error) {
+	data, err := os.ReadFile(jsonFilePath)
+	defer func(name string) {
+		err := os.Remove(name)
```
Comment (jba) [inline internal/config/state.go:230]: if err := ...; err != nil

File: internal/config/state.go [hunk 16]
```diff
@@ -218,3 +220,47 @@ func isValidImage(image string) bool {
 
 	return ref != "" && tag != ""
 }
+
+// ReadResponse reads the library state from configure-response.json.
+//
+// The response file is removed afterwards.
+func ReadResponse(contentLoader func(data []byte, state *LibraryState) error, jsonFilePath string) (*LibraryState, error) {
+	data, err := os.ReadFile(jsonFilePath)
+	defer func(name string) {
```
Comment (jba) [inline internal/config/state.go:229]: You don't need to pass jsonFilePath as an arg. Just defer func() {...}()

File: internal/config/state.go [hunk 17]
```diff
@@ -218,3 +220,47 @@ func isValidImage(image string) bool {
 
 	return ref != "" && tag != ""
 }
+
+// ReadResponse reads the library state from configure-response.json.
+//
+// The response file is removed afterwards.
+func ReadResponse(contentLoader func(data []byte, state *LibraryState) error, jsonFilePath string) (*LibraryState, error) {
```
Comment (jba) [inline internal/config/state.go:227]: FYI, you can omit "data" and "state" in the func on this line to make it shorter. But it's also OK to leave them there.

File: internal/config/state.go [hunk 18]
```diff
@@ -218,3 +220,47 @@ func isValidImage(image string) bool {
...
+	return libraryState, nil
+}
+
+// WriteLibrarianState writes the given librarian state to a yaml file.
+func WriteLibrarianState(contentParser func(state *LibrarianState) ([]byte, error), state *LibrarianState, yamlFilePath string) error {
+	yamlFile, err := os.Create(yamlFilePath)
+	if err != nil {
+		return fmt.Errorf("failed to create librarian state file, path: %s, error: %w", yamlFilePath, err)
+	}
+	defer yamlFile.Close()
```
Comment (jba) [inline internal/config/state.go:254]: Check error on Close when writing to a file.

File: internal/config/state_test.go [hunk 19]
```diff
@@ -323,3 +332,241 @@ func TestIsValidImage(t *testing.T) {
...
+			wantState:    nil,
+		},
+	} {
+		t.Run(test.name, func(t *testing.T) {
+			tempDir := t.TempDir()
+			if test.name == "invalid_file_name" {
+				filePath := filepath.Join(tempDir, "my\x00file.json")
+				_, err := ReadResponse(contentLoader, filePath)
+				if err == nil {
+					t.Errorf("readResponse() expected an error but got nil")
```
Comment (jba) [inline internal/config/state_test.go:385]: nit: t.Error

File: internal/config/state_test.go [hunk 20]
```diff
@@ -323,3 +332,241 @@ func TestIsValidImage(t *testing.T) {
...
+				return
+			}
+
+			if test.name == "invalid content loader" {
+				invalidContentLoader := func(data []byte, state *LibraryState) error {
+					return errors.New("simulated Unmarshal error")
+				}
+				dst := fmt.Sprintf("%s/copy.json", os.TempDir())
+				if err := copyFile(dst, test.jsonFilePath); err != nil {
+					t.Errorf("copyFile() failed, error %q", err)
```
Comment (jba) [inline internal/config/state_test.go:401]: If copyFile returned this error, you could have written `t.Error(err)`.
Although this should probably be `t.Fatal` since the rest of the test doesn't make sense if this fails.

File: internal/config/state_test.go [hunk 21]
```diff
@@ -323,3 +332,241 @@ func TestIsValidImage(t *testing.T) {
...
+			}
+
+			if diff := cmp.Diff(string(wantBytes), string(gotBytes)); diff != "" {
+				t.Errorf("Generated YAML mismatch (-want +got):\n%s", diff)
+			}
+		})
+	}
+}
+
+func copyFile(dst, src string) (err error) {
```
Comment (jba) [inline internal/config/state_test.go:551]: If the top of this function had the following, then callers wouldn't need to annotate the error:
```
defer func() {
    if err != nil { err = fmt.Errorf("copyFile(%q, %q): %w", dst, src, err) }
}()
```

File: internal/config/state_test.go [hunk 22]
```diff
@@ -323,3 +332,241 @@ func TestIsValidImage(t *testing.T) {
...
+	destinationFile, err := os.Create(dst)
+	if err != nil {
+		return err
+	}
+
+	defer func() {
+		err = errors.Join(err, destinationFile.Close())
+	}()
+
+	if _, err := io.Copy(destinationFile, sourceFile); err != nil {
```
Comment (jba) [inline internal/config/state_test.go:567]: _, err := io.Copy(...)
return err

**Review by jba — CHANGES_REQUESTED** [review]
Sorry, a lot more comments!
I hope you're enjoying learning a lot about Go style and idioms!
(Well maybe not _enjoying_...)

File: internal/docker/docker.go [hunk 23]
```diff
@@ -217,7 +218,39 @@ func (c *Docker) Configure(ctx context.Context, request *ConfigureRequest) error
...
+		request.State.Libraries[i] = libraryState
+	}
+
+	// Write the updated librarian state to state.yaml.
+	if err := config.WriteLibrarianState(
+		func(state *config.LibrarianState) ([]byte, error) {
+			return yaml.Marshal(state)
+		},
+		request.State,
+		filepath.Join(request.RepoDir, config.LibrarianDir, config.PipelineStateFile)); err != nil {
```
Comment (zhumin8) [inline internal/docker/docker.go:249]: This parameter can be just `repodir` instead of `yamlFilePath`, and path constructed inside WriteLibrarianState. This way config.PipelineStateFile does not need to be exported?

File: internal/docker/docker.go [hunk 24]
```diff
@@ -192,17 +193,17 @@ func (c *Docker) Build(ctx context.Context, request *BuildRequest) error {
 
 // Configure configures an API within a repository, either adding it to an
 // existing library or creating a new library.
-func (c *Docker) Configure(ctx context.Context, request *ConfigureRequest) error {
-	jsonFilePath := filepath.Join(request.RepoDir, config.LibrarianDir, config.ConfigureRequest)
-	if err := writeRequest(request.State, request.LibraryID, jsonFilePath); err != nil {
-		return err
+func (c *Docker) Configure(ctx context.Context, request *ConfigureRequest) (string, error) {
```
Comment (zhumin8) [inline internal/docker/docker.go:196]: nit: update description with return type change

File: internal/docker/docker.go [hunk 25]
```diff
@@ -192,17 +193,17 @@ func (c *Docker) Build(ctx context.Context, request *BuildRequest) error {
...
+	if err := writeRequest(request.State, request.LibraryID, requestFilePath); err != nil {
+		return "", err
 	}
 	defer func(name string) {
 		err := os.Remove(name)
 		if err != nil {
 			slog.Warn("fail to remove file", slog.String("name", name), slog.Any("err", err))
 		}
-	}(jsonFilePath)
+	}(requestFilePath)
```
Comment (zhumin8) [inline internal/docker/docker.go:206]: is this `requestFilePath` unused?

File: internal/config/state.go (hunk 17 above)
Comment (zhumin8) [inline internal/config/state.go:228]: `ReadResponse` and `WriteLibrarianState` are more suited in librarian/state.go, where load related functions are already located.
followup to https://github.com/googleapis/librarian/pull/989#discussion_r2242731498

File: internal/config/state_test.go (hunk 19 above)
Comment (JoeWang1127) [reply internal/config/state_test.go]: Done

File: internal/config/state_test.go (hunk 20 above)
Comment (JoeWang1127) [reply internal/config/state_test.go]: Done

File: internal/config/state_test.go (hunk 21 above)
Comment (JoeWang1127) [reply internal/config/state_test.go:551]: Done

File: internal/config/state_test.go (hunk 22 above)
Comment (JoeWang1127) [reply internal/config/state_test.go]: Done

File: internal/config/state.go (hunk 15 above)
Comment (JoeWang1127) [reply internal/config/state.go]: Done

File: internal/config/state.go (hunk 18 above)
Comment (JoeWang1127) [reply internal/config/state.go]: Done

File: internal/docker/docker.go (hunk 24 above)
Comment (JoeWang1127) [reply internal/docker/docker.go:197]: Done.

File: internal/docker/docker.go (hunk 23 above)
Comment (JoeWang1127) [reply internal/docker/docker.go]: Done.

File: internal/librarian/state.go [hunk 26]
```diff
@@ -28,10 +29,12 @@ import (
 	"gopkg.in/yaml.v3"
 )
 
-const pipelineStateFile = "state.yaml"
-const pipelineConfigFile = "pipeline-config.json"
-const serviceConfigType = "type"
-const serviceConfigValue = "google.api.Service"
+const (
+	pipelineStateFile  = "state.yaml"
```
Comment (zhumin8) [inline internal/librarian/state.go:33]: We have both pipelineStateFile and config.PipelineStateFile now. I think we just need this one and do not need to export it?

File: internal/librarian/state_test.go [hunk 27]
```diff
@@ -257,3 +263,256 @@ func TestPopulateServiceConfig(t *testing.T) {
...
+	contentLoader := func(data []byte, state *config.LibraryState) error {
+		return json.Unmarshal(data, state)
+	}
+	for _, test := range []struct {
+		name         string
+		jsonFilePath string
+		wantState    *config.LibraryState
+	}{
+		{
+			name:         "successful-unmarshal",
```
Comment (zhumin8) [inline internal/librarian/state_test.go:278]: nit: Test case names formats are a bit mixed in this file, can we adopt "descriptive strings with spaces" for consistency?

File: internal/librarian/state.go (hunk 26 above)
Comment (JoeWang1127) [reply internal/librarian/state.go:30]: Done.
