### PR TITLE
fix: group commit msg if they have the same piper id and subject

### LINKED ISSUE #2470: librarian: `failed to create pull request. Message:body is too long (maximum is 65536 characters)}`
See the failure below from the most recent `generate` job for Python

`Failed: 83af459f-3139-447e-ba82-a33d0711e148`

```
time=2025-10-02T12:37:42.674Z level=INFO msg="Successfully pushed changes" refSpec=+refs/heads/librarian-20251002T123648Z:refs/heads/librarian-20251002T123648Z
time=2025-10-02T12:37:44.343Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:44.344Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:44.494Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:44.494Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:44.748Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:44.748Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:44.868Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:44.868Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:45.031Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:45.031Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:45.149Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:45.149Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:45.343Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:45.343Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:45.463Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:45.463Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:45.651Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:45.651Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:45.812Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:45.812Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:46.588Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=a6fb279349101a2e53aaad4c9f02c57871812153
time=2025-10-02T12:37:46.588Z level=WARN msg="bodyLine is not a header" bodyLine="Clients can now manage Iceberg Rest Catalogs." hash=a6fb279349101a2e53aaad4c9f02c57871812153
time=2025-10-02T12:37:46.827Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:46.827Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:46.945Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:46.945Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:47.137Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:47.137Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:47.297Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:47.297Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:47.875Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:47.875Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:48.291Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:48.291Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:49.903Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:49.903Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:50.115Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:50.115Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:51.769Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:51.769Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:51.876Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:51.876Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:52.126Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:52.126Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:52.255Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:52.255Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:52.525Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:52.525Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:52.628Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:52.628Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=888ae95dd6125f754650d55410b8c117b618a268
time=2025-10-02T12:37:52.867Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:52.867Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:53.093Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:53.093Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:53.254Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:53.254Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:53.373Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:53.373Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:53.584Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:53.584Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:53.891Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:53.891Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:54.055Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:54.055Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:54.170Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:54.170Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:54.395Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:54.395Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:54.619Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:54.619Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:54.838Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:54.838Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:55.042Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:55.042Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:55.156Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:55.156Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:37:55.524Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:55.524Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:55.647Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:55.647Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:56.111Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:56.111Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:56.236Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:56.236Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:56.356Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:56.356Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:56.480Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:56.480Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:56.607Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:56.607Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:56.777Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:56.777Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:56.903Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:56.904Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:57.058Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:57.058Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:57.222Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:57.222Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:57.381Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:57.382Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:57.498Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:57.498Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:57.671Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:57.671Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:57.822Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:57.822Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:58.030Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:58.030Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:58.201Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:58.201Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:58.318Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:58.318Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:58.512Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:58.512Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:58.628Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:58.628Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:58.755Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:58.755Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:58.943Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:58.943Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:59.096Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:59.096Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:59.266Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:59.266Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:59.390Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:59.390Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:59.513Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:59.513Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:59.679Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:59.679Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:59.807Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:59.807Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:59.932Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:37:59.932Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:38:00.107Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:38:00.107Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:38:00.233Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:38:00.233Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:38:00.366Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:38:00.366Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=36533b09a6b383f3c30d13c3c26092154ecf5388
time=2025-10-02T12:38:00.546Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:38:00.546Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:38:00.661Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:38:00.661Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:38:00.821Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:38:00.821Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:38:00.975Z level=WARN msg="bodyLine is not a header" bodyLine="" hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:38:00.975Z level=WARN msg="bodyLine is not a header" bodyLine="An update to Go gRPC Protobuf generation will change service registration function signatures to use an interface instead of a concrete type in generated .pb.go service files. This change should affect very few client library users. See release notes advisories in https://github.com/googleapis/google-cloud-go/pull/11025." hash=0a0dffc19bed400afdeec0f67b1726b6b23173fb
time=2025-10-02T12:38:00.978Z level=INFO msg="skip getting last generated commit" library=google-cloud-source-context
time=2025-10-02T12:38:00.978Z level=INFO msg="skip getting last generated commit" library=google-cloud-iam-logging
time=2025-10-02T12:38:00.979Z level=INFO msg="skip getting last generated commit" library=google-cloud-public-ca
time=2025-10-02T12:38:00.979Z level=INFO msg="skip getting last generated commit" library=google-cloud-recommendations-ai
time=2025-10-02T12:38:00.988Z level=INFO msg="Creating PR" branch=librarian-20251002T123648Z base=main title="chore: librarian generate pull request: 20251002T123648Z"
time=2025-10-02T12:38:01.733Z level=INFO msg="failed to create pull request: POST https://api.github.com/repos/googleapis/google-cloud-python/pulls: 422 Validation Failed [{Resource:Issue Field:body Code:custom Message:body is too long (maximum is 65536 characters)}]"

```

### PR DESCRIPTION
**Pull request by JoeWang1127**
Example generation PR: https://github.com/JoeWang1127/google-cloud-python/pull/3
Example release PR: https://github.com/JoeWang1127/google-cloud-python/pull/4

Fixes #2470

### CODE REVIEW

File: internal/librarian/release_notes.go [hunk 1]
```diff
@@ -237,6 +237,46 @@ func findLatestGenerationCommit(repo gitrepo.Repository, state *config.Librarian
 	return res, nil
 }
 
+// groupByIDAndSubject aggregates conventional commits for ones have the same Piper ID and subject in the footer.
+func groupByIDAndSubject(commits []*conventionalcommits.ConventionalCommit) []*conventionalcommits.ConventionalCommit {
+	idToCommits := make(map[string][]*conventionalcommits.ConventionalCommit)
```
Comment (codyoss) [inline internal/librarian/release_notes.go:242]: Can we simplify this to be a `map[string]*conventionalcommits.ConventionalCommit` and just keep appending to the Library-IDs if we have seen this piper-id before?

File: internal/librarian/release_notes.go [hunk 2]
```diff
@@ -237,6 +237,46 @@ func findLatestGenerationCommit(repo gitrepo.Repository, state *config.Librarian
...
+			commit.Footers = make(map[string]string)
+			commit.Footers["Library-IDs"] = commit.LibraryID
+			singletons = append(singletons, commit)
+			continue
+		}
+
+		id, ok := commit.Footers["PiperOrigin-RevId"]
+		if !ok {
+			commit.Footers["Library-IDs"] = commit.LibraryID
+			singletons = append(singletons, commit)
```
Comment (codyoss) [inline internal/librarian/release_notes.go:258]: These can just be directly added to the response instead of creating the singletons slice.

File: internal/librarian/release_notes.go [hunk 3]
```diff
@@ -237,6 +237,46 @@ func findLatestGenerationCommit(repo gitrepo.Repository, state *config.Librarian
 	return res, nil
 }
 
+// groupByIDAndSubject aggregates conventional commits for ones have the same Piper ID and subject in the footer.
+func groupByIDAndSubject(commits []*conventionalcommits.ConventionalCommit) []*conventionalcommits.ConventionalCommit {
+	idToCommits := make(map[string][]*conventionalcommits.ConventionalCommit)
+	var singletons []*conventionalcommits.ConventionalCommit
+	for i := range len(commits) {
```
[the remark this answers is not in the document]
Comment (JoeWang1127) [reply internal/librarian/release_notes.go:244]: Done.

File: internal/librarian/release_notes.go (hunk 2 above)
Comment (JoeWang1127) [reply internal/librarian/release_notes.go:258]: Done.

File: internal/librarian/release_notes.go [hunk 4]
```diff
@@ -182,7 +182,7 @@ func formatGenerationPRBody(repo gitrepo.Repository, state *config.LibrarianStat
 	// because this function will return early if no conventional commit is found
 	// since last generation.
 	startSHA := startCommit.Hash.String()
-
+	allCommits = groupByIDAndSubject(allCommits)
```
[the remark this answers is not in the document]
Comment (JoeWang1127) [reply internal/librarian/release_notes.go]: Done.

File: internal/librarian/release_notes.go (hunk 1 above)
Comment (JoeWang1127) [reply internal/librarian/release_notes.go:243]: I've tried this approach but it was not as simple as the current one.

You need to check whether the `Footer` map exists and use `fmt.Sprintf` or StringBuilder to append the string.
