### PR TITLE
fix(internal/librarian/java): clean to use derived module names

### LINKED ISSUE #5417: java: clean logic should use derived module names
Clean logic should use derived module names from internal/librarian/java/maven_coordinate.go, instead of library names and hardcoded guess for proto- and grpc- modules.

### PR DESCRIPTION
**Pull request by zhumin8**
Change clean to derive clean patterns with `DeriveAPICoordinates` so that it uses same source as generate. Also changed clean scope to /src dirs under each module, to be consistent with that owlbot.yaml does today.

Fix #5417

### CODE REVIEW

File: internal/librarian/java/clean.go [hunk 1]
```diff
@@ -58,6 +50,27 @@ func Clean(library *config.Library) error {
...
+		ac := DeriveAPICoordinates(lc, version, javaAPI)
+		if ac.Proto.ArtifactID != "" {
+			patterns[filepath.Join(ac.Proto.ArtifactID, "src")] = true
+		}
+		if ac.GRPC.ArtifactID != "" {
+			patterns[filepath.Join(ac.GRPC.ArtifactID, "src")] = true
+		}
+	}
+	return patterns
+}
```
[the remark this answers is not in the document]
Comment (zhumin8) [reply internal/librarian/java/clean.go:72]: This is to keep consistent with existing from owlbot.yaml, see template [here](https://github.com/googleapis/google-cloud-java/blob/main/sdk-platform-java/hermetic_build/library_generation/templates/owlbot.yaml.monorepo.j2).
However, this **may** change (https://github.com/googleapis/librarian/issues/4559). I want to get this update in and test out.

File: internal/librarian/java/clean.go [hunk 2]
```diff
@@ -58,6 +50,27 @@ func Clean(library *config.Library) error {
 	return nil
 }
 
+func cleanPatterns(library *config.Library) map[string]bool {
+	lc := DeriveLibraryCoordinates(library)
```
Comment (JoeWang1127) [inline internal/librarian/java/clean.go]:
```suggestion
	libCoordinates := DeriveLibraryCoordinates(library)
```

File: internal/librarian/java/clean.go [hunk 3]
```diff
@@ -58,6 +50,27 @@ func Clean(library *config.Library) error {
...
+	patterns := map[string]bool{
+		filepath.Join(lc.GAPIC.ArtifactID, "src"):         true,
+		filepath.Join("samples", "snippets", "generated"): true,
+		".repo-metadata.json":                             true,
+	}
+	for _, api := range library.APIs {
+		javaAPI := ResolveJavaAPI(library, api)
+		version := filepath.Base(api.Path)
+		ac := DeriveAPICoordinates(lc, version, javaAPI)
```
Comment (JoeWang1127) [inline internal/librarian/java/clean.go]:
```suggestion
		apiCoordinates := DeriveAPICoordinates(lc, version, javaAPI)
```

File: internal/librarian/java/clean.go [hunk 4]
```diff
@@ -58,6 +50,27 @@ func Clean(library *config.Library) error {
 	return nil
 }
 
+func cleanPatterns(library *config.Library) map[string]bool {
+	lc := DeriveLibraryCoordinates(library)
+	patterns := map[string]bool{
+		filepath.Join(lc.GAPIC.ArtifactID, "src"):         true,
```
Comment (JoeWang1127) [inline internal/librarian/java/clean.go]: Do we need to add this pattern if the api is proto-only?

Can we move this line to the for loop in line 60?

Comment (zhumin8) [reply internal/librarian/java/clean.go]: Good point. Created a followup https://github.com/googleapis/librarian/issues/5430 to check if logic is compatible with proto only case.

**Review by JoeWang1127 — APPROVED** [review]
