### PR TITLE
fix: get conventional commits from source repository

### LINKED ISSUE #1866: librarian: generation is looking for conventional commits in the wrong repo (I believe)
Having just updated to the latest version of the CLI, I'm getting errors like this when generating Go libraries:

> failed to fetch conventional commits for library, maps: failed to get commits for library maps: did not find commit 6914b3387f851ae8411231e4e57fefa5290eb9f8 when iterating

I believe the issue is in #1837, and I *think* it's for two reasons:

- It's looking in the language repo, not the googeapis repo
- It's looking for changes in the source roots of the library, not the source paths of the APIs

I may have misunderstood, of course.

Marking as p1 as I'd expect generation to always fail at the moment - the commit stored in state.last_generated_commit will *never* be in the language repo.

### PR DESCRIPTION
**Pull request by JoeWang1127**
Function `updateChangesSinceLastGeneration` may not be needed since we don't need to pass api changes to language container.

Fixes #1866

### CODE REVIEW

File: internal/librarian/generate_test.go [hunk 1]
```diff
@@ -1468,3 +1481,139 @@ func TestCompileRegexps(t *testing.T) {
...
+					"api/another/path": {
+						{
+							Message: "fix: a bug fix\n\nThis is another body.\n\nPiperOrigin-RevId: 573342",
+							Hash:    hash2,
+						},
+					},
+				},
+				ChangedFilesInCommitValueByHash: map[string][]string{
+					hash1.String(): {
+						"api/one//path/file.txt",
```
Comment (jskeet) [inline internal/librarian/generate_test.go:1535]: Are the double forward slashes here and below deliberate?

File: internal/librarian/release_please_lite.go [hunk 2]
```diff
@@ -39,9 +39,14 @@ func GetConventionalCommitsSinceLastRelease(repo gitrepo.Repository, library *co
...
-// the given library since the last generation.
+// all API paths in given library since the last generation.
 func GetConventionalCommitsSinceLastGeneration(repo gitrepo.Repository, library *config.LibraryState) ([]*conventionalcommits.ConventionalCommit, error) {
-	commits, err := repo.GetCommitsForPathsSinceCommit(library.SourceRoots, library.LastGeneratedCommit)
+	apiPaths := make([]string, 0)
+	for _, oneAPI := range library.APIs {
+		apiPaths = append(apiPaths, oneAPI.Path)
+	}
+
+	commits, err := repo.GetCommitsForPathsSinceCommit(apiPaths, library.LastGeneratedCommit)
```
Comment (jskeet) [inline internal/librarian/release_please_lite.go:49]: What would you expect to happen if LastGeneratedCommit is empty? (I'm expecting that to be common when onboarding a new library.) I think in that case we should just not bother looking for anything.

**Review by jskeet — COMMENTED** [review]
One comment on the prod code - I'm not sure I'm qualfied to review the test code here.

File: internal/librarian/release_please_lite.go (hunk 2 above)
Comment (JoeWang1127) [reply internal/librarian/release_please_lite.go:49]: It's a good point.

How about I file a new issue and fix it in another PR?
