### PR TITLE
fix(internal/librarian/java): recursively gather protos and sort

### LINKED ISSUE #4198: java: determine if sort needed for proto files
In java hermetic_build generate, it sorts proto files binary order with `LC_COLLATE=C sort`. This is likely to ensure gapic_metadata.json has a deterministic and correct service order.
Code for ref: https://github.com/googleapis/sdk-platform-java/blob/d9b39ed775795c44b1fd778d767f06aa706f6ee9/hermetic_build/library_generation/generate_library.sh#L123

when comparing diff for migration, find concrete case if this sort is needed (likely yes) and implement similar logic to librarian code.

### PR DESCRIPTION
**Pull request by zhumin8**
Recursively gather protos for generate, to include protos in nested dirs, sort to maintain deterministic order.

For #5380
Fix #4198

### CODE REVIEW

File: internal/librarian/java/generate.go [hunk 1]
```diff
@@ -305,3 +308,37 @@ func findBOMVersion(cfg *config.Config) (string, error) {
...
+		if err != nil {
+			return err
+		}
+		if d.IsDir() {
+			if !recursive && path != root {
+				return filepath.SkipDir
+			}
+			return nil
+		}
+		if d.Type().IsRegular() && filepath.Ext(path) == ".proto" {
```
[the remark this answers is not in the document]
Comment (zhumin8) [reply internal/librarian/java/generate.go:327]: I don't think we use symlinks for proto files.

File: internal/librarian/java/generate_test.go [hunk 2]
```diff
@@ -749,3 +749,76 @@ func TestCollectJavaFiles(t *testing.T) {
...
+			relPath: "google/cloud/location",
+			want: []string{
+				filepath.Join(tmpDir, "google/cloud/location/locations.proto"),
+				filepath.Join(tmpDir, "google/cloud/location/sub/sub.proto"),
+			},
+		},
+	} {
+		t.Run(test.name, func(t *testing.T) {
+			root := filepath.Join(tmpDir, test.relPath)
+			if test.relPath == "google/cloud/aiplatform/v1" {
```
Comment (JoeWang1127) [inline internal/librarian/java/generate_test.go]: How about create some proto files within `google/cloud/aiplatform/v1` so that you don't need this if condition.

File: internal/librarian/java/generate.go [hunk 3]
```diff
@@ -305,3 +309,37 @@ func findBOMVersion(cfg *config.Config) (string, error) {
 	}
 	return "", errBOMVersionMissing
 }
+
+// gatherProtos returns a sorted list of proto files in the given root directory,
+// ensuring that subpackage protos (e.g., in a "schema" directory) are included
```
Comment (JoeWang1127) [inline internal/librarian/java/generate.go:309]: Why do you need to mention `schema` in the comment?

File: internal/librarian/java/generate.go [hunk 4]
```diff
@@ -305,3 +309,37 @@ func findBOMVersion(cfg *config.Config) (string, error) {
...
+// in the generation.
+//
+// recursion is disabled for certain base paths (google/api, google/cloud, google/rpc).
```
Comment (JoeWang1127) [inline internal/librarian/java/generate.go]:
```suggestion
// recursion is disabled for certain base paths in nonRecursivePaths.
```

**Review by quirogas — APPROVED** [review]

File: internal/librarian/java/generate_test.go (hunk 2 above)
Comment (zhumin8) [reply internal/librarian/java/generate_test.go]: done

File: internal/librarian/java/generate.go (hunk 3 above)
Comment (zhumin8) [reply internal/librarian/java/generate.go:309]: as example.

**Review by JoeWang1127 — APPROVED** [review]
