### PR TITLE
fix(internal/librarian): handle generation for all libraries vs. single library according to flags

### LINKED ISSUE #929: librarian: generate should handle generation for all libraries
The generate command should handle the previous "configure, generate, and update-apis commands". 

Logic from `update-apis` around looping and generate for all libraries defined in `state.yaml` is missing.

For reference, decision diagram from [go/librarian:generate-command](http://go/librarian:generate-command)
```
┣━━ Determine Target Libraries: The tool checks how to scope its work.
┃   ┣━━ IF the `--library=<library_name>` or `--api=<api_path>` flags are set:
┃   ┃   ┗━━ The process will run for one specific library.
┃   ┗━━ ELSE (no `--library` or `--api` flag):
┃       ┗━━ The process will run for ALL libraries defined in `state.yaml`
```

blocked by #955

### LINKED ISSUE #931: librarian: configure should run when libraryID is not configured in state.yaml and add the entry
Missed in #898 review. runConfigureCommand() is only invoked when library is not found in state.yaml

https://github.com/googleapis/librarian/blob/10e32185114ee020512b1e9fb1448486b0e45766/internal/librarian/generate.go#L166-L175

Then this logic leads into error
https://github.com/googleapis/librarian/blob/10e32185114ee020512b1e9fb1448486b0e45766/internal/librarian/generate.go#L442-L445

Also, configure should create a LibraryState skeleton to pass down to container via configure-request.json

cc. @cuiy0006

### LINKED ISSUE #955: librarian: missing library flag
[go/librarian:cli-reimagined](http://goto.google.com/librarian:cli-reimagined)

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-0f373a3c-7fff-41f8-146a-50fd8dc51d81"><div dir="ltr" style="margin-left:0pt;" align="center">
generate flags | description | required
-- | -- | --
library | The library ID to generate (e.g. google-cloud-secretmanager-v1 ). This usually corresponds to a releasable language unit -- for Go this would be a Go module or for dotnet the name of a NuGet package. If neither this nor api is specified all currently managed libraries will be regenerated. | false

</div></b>

related: #929

### PR DESCRIPTION
**Pull request by zhumin8**
Add flow control to handle both single library generation and all configured libraries generation.

- Add "--library" flag and config
- removed redundant/outdated `detectIfLibraryConfigured`
- generate logic addition/change:
  - generate single library if  `api` or `library` specified, extra step to configure new library when both  `api` and `library` specified and library not present in state.yaml
  - loop though state and generate for all existing libraries when no `api` or `library` specified.
- `runConfigureCommand` adds library entry to state, and calls containerClient.Configure with correct request/ctx.
- add test cases, updates to some log entries, and update command doc to reflect changes
- remove some unused code

Reference for reviewers: decision diagram in [go/librarian:generate-command](http://go/librarian:generate-command)

Fixes #929 
Fixes #955
Fixes #931

### CODE REVIEW

File: internal/config/config.go [hunk 1]
```diff
@@ -93,12 +93,11 @@ type Config struct {
...
 	Image string
 
-	// LibrarianRepository specifies the repository where Librarian-related assets
-	// are stored.
-	//
-	// LibrarianRepository is fetched from the LIBRARIAN_REPOSITORY environment
-	// variable.
-	LibrarianRepository string
+	// Library is the library ID to generate (e.g. google-cloud-secretmanager-v1 ).
+	//  This usually corresponds to a releasable language unit -- for Go this would
```
Comment (JoeWang1127) [inline internal/config/config.go:97]:
```suggestion
	// This usually corresponds to a releasable language unit -- for Go this would
```

File: internal/librarian/generate.go [hunk 2]
```diff
@@ -157,35 +149,70 @@ func newGenerateRunner(cfg *config.Config) (*generateRunner, error) {
...
+		}
+		if err := r.generateSingleLibrary(ctx, libraryID, outputDir); err != nil {
 			return err
 		}
+	} else {
+		for _, library := range r.state.Libraries {
+			if err := r.generateSingleLibrary(ctx, library.ID, outputDir); err != nil {
+				// TODO(https://github.com/googleapis/librarian/issues/983): record failure and report in PR body when applicable
+				slog.Error("failed to generate library", "id", library.ID, "err", err)
+				continue
```
Comment (JoeWang1127) [inline internal/librarian/generate.go:180]: Is this redundant?

**Review by JoeWang1127 — COMMENTED** [review]
Added minor suggestions.

File: internal/librarian/generate.go (hunk 2 above)
Comment (zhumin8) [reply internal/librarian/generate.go:180]: Can you elaborate what you think is redundant?

Comment (JoeWang1127) [reply internal/librarian/generate.go:180]: I think `continue` is redundant. There's no other code to execute in the loop.

File: internal/librarian/generate.go [hunk 3]
```diff
@@ -157,35 +149,70 @@ func newGenerateRunner(cfg *config.Config) (*generateRunner, error) {
...
 		return err
 	}
 	slog.Info("Code will be generated", "dir", outputDir)
 
-	configured, err := r.detectIfLibraryConfigured(ctx)
-	if err != nil {
-		return err
-	}
+	if r.cfg.API != "" || r.cfg.Library != "" {
+		var libraryID string
```
[the remark this answers is not in the document]
Comment (zhumin8) [reply internal/librarian/generate.go]: done [1d57504](https://github.com/googleapis/librarian/pull/977/commits/1d57504df1de6ef1a7870f2f9609db552944c55f)

File: internal/config/config.go (hunk 1 above)
Comment (zhumin8) [reply internal/config/config.go]: done [1d57504](https://github.com/googleapis/librarian/pull/977/commits/1d57504df1de6ef1a7870f2f9609db552944c55f)

File: internal/librarian/generate.go (hunk 2 above)
Comment (zhumin8) [reply internal/librarian/generate.go]: removed.

File: internal/librarian/generate.go [hunk 4]
```diff
@@ -157,35 +149,70 @@ func newGenerateRunner(cfg *config.Config) (*generateRunner, error) {
...
+}
 
-	if err := r.runBuildCommand(ctx, libraryID); err != nil {
+// generateSingleLibrary manages the generation of a single client library.
+//
+// It can either configure a new library if the API and library names both are specified
+// in the configuration, or regenerate an existing library if a libraryID is provided.
+// After ensuring the library is configured, it runs the generation and build commands.
+func (r *generateRunner) generateSingleLibrary(ctx context.Context, libraryID, outputDir string) error {
+	if r.cfg.API != "" && r.cfg.Library != "" {
```
[the remark this answers is not in the document]
Comment (zhumin8) [reply internal/librarian/generate.go]: updated in [66a848b](https://github.com/googleapis/librarian/pull/977/commits/66a848b0fac17afae57d8a6e7eee498ff5c3bc48)

**Review by JoeWang1127 — APPROVED** [review]

**Review by codyoss — DISMISSED** [review]

**Review by codyoss — APPROVED** [review]
