### PR TITLE
fix(internal/surfer): track target vs current for real APIs and decouple unit tests

### LINKED ISSUE #5373: surfer: move test apis into golden directory
Move test apis into golden directory so we can compare against target output

### PR DESCRIPTION
**Pull request by sarahheacock**
Golden file tests are updated to track target versus current generated outputs for real APIs including parallelstore, iam, and seclm. This allows verifying that Librarian output matches the target baseline or identifying intentional deviations. Unit tests in surfer_test.go are decoupled from checked-in production configurations by using dynamically generated temporary files for setup. Blockchainvalidator removed since it is not available in googleapis

Fixes https://github.com/googleapis/librarian/issues/5373

### CODE REVIEW

File: internal/surfer/gcloud/command_writer_test.go
Comment (quirogas) [inline internal/surfer/gcloud/command_writer_test.go:1]: Why are we removing the test for validating the YAML schema?

File: internal/surfer/gcloud/command_writer_test.go [hunk 1]
```diff
@@ -81,60 +78,6 @@ func TestWritePartialFile_Output(t *testing.T) {
...
-				t.Fatal(err)
-			}
-
-			if diff := cmp.Diff(commands, roundTripped); diff != "" {
-				t.Errorf("mismatch (-want +got):\n%s", diff)
-			}
-		})
-	}
-}
-
```
Comment (quirogas) [inline internal/surfer/gcloud/command_writer_test.go:137]: Nit: If we are deleting tests, I think it would be helpful to understand the reasoning. I'm assuming this removal is intended to prioritize golden tests? Will we lose coverage or signaling if we break the schema?

File: internal/surfer/gcloud/provider/loader.go [hunk 2]
```diff
@@ -68,5 +75,22 @@ func ReadGcloudConfig(path string) (*Config, error) {
...
+		if p.Type == "" {
+			return fmt.Errorf("resource_patterns[%d].type is required", i)
+		}
+		if len(p.Patterns) == 0 {
+			return fmt.Errorf("resource_patterns[%d].patterns must not be empty", i)
+		}
+	}
+
+	return nil
+}
```
Comment (quirogas) [inline internal/surfer/gcloud/provider/loader.go:96]: I have two thoughts here:

1. What if we implemented a Validate() error method directly on the Config struct and its
     nested types?  It would move the validation logic where the data is defined. 
2. should we also validate ServiceName, API.Name, and Selector strings?

**Review by quirogas — APPROVED** [review]
LGTM!

File: internal/surfer/gcloud/command_writer_test.go (hunk 1 above)
Comment (sarahheacock) [reply internal/surfer/gcloud/command_writer_test.go:137]: Correct, this was redundant of the golden tests and was a little confusing. It took me a minute to understand that it was looking for missing fields from just the command schema. This was a good starting point but the golden tests are a better fit because they verify that the actual generated output (which implies a correct schema), rather than just checking if we can parse and serialize a specific API file.

File: internal/surfer/gcloud/command_writer_test.go
Comment (sarahheacock) [reply internal/surfer/gcloud/command_writer_test.go:1]: Same answer as below

File: internal/surfer/gcloud/provider/loader.go (hunk 2 above)
Comment (sarahheacock) [reply internal/surfer/gcloud/provider/loader.go:96]: I think those are good ideas. I think you're right we'll need ServiceName, API.Name, selector. However, given the slight direction change of the project where we might be mass onboarding, I didn't want to add any premature validation for the time being
