### PR TITLE
fix(internal/librarian/java): move run owlbot.py logic to per library instead of per api 

### LINKED ISSUE #5022: java: move run owlbot.py logic to per library instead of per api
run owlbot.py should be run once for the whole library, not per api.

### PR DESCRIPTION
**Pull request by zhumin8**
Run owlbot.py logic should be run once per library to be efficient, not per api. Removed some test setup steps that are no longer needed, and added a test on error cases for the new postProcessLibrary.

Fix #5022

### CODE REVIEW

File: internal/librarian/java/postprocess_test.go [hunk 1]
```diff
@@ -282,6 +264,148 @@ func TestCopyProtos_ErrorCase(t *testing.T) {
...
+				test.setup(t, outDir)
+			}
+			params := libraryPostProcessParams{
+				cfg:      test.cfg,
+				library:  library,
+				outDir:   outDir,
+				metadata: &repoMetadata{NamePretty: "Secret Manager"},
+			}
+			err := postProcessLibrary(t.Context(), params)
+			if test.wantErr == nil {
```
Comment (JoeWang1127) [inline internal/librarian/java/postprocess_test.go]: Do you need this line since these tests return error?
