### PR TITLE
fix(tool/cmd/migrate): add hardcoded transport override for Java

### LINKED ISSUE #5554: java: java-alloydb-connectors repo-metadata transport diff
Using default transport grpc+rest, generated repo-metadata has ` "transport": "both",`, expecting ` "transport": "grpc",`.

Note `java-alloydb-connectors` is a proto only library. So the transport setting does not actually affects generated code other than .repo-metadata.json and README.

Here is current config for this library:
```
  - name: alloydb-connectors
    version: 0.67.0-SNAPSHOT
    apis:
      - path: google/cloud/alloydb/connectors/v1
      - path: google/cloud/alloydb/connectors/v1beta
      - path: google/cloud/alloydb/connectors/v1alpha
    java:
      api_id_override: connectors.googleapis.com
      api_description_override: AlloyDB is a fully-managed, PostgreSQL-compatible database for demanding transactional workloads. It provides enterprise-grade performance and availability while maintaining 100% compatibility with open-source PostgreSQL.
      name_pretty_override: AlloyDB connectors
      java_apis:
        - path: google/cloud/alloydb/connectors/v1
          proto_only: true
          samples: false
        - path: google/cloud/alloydb/connectors/v1alpha
          proto_only: true
          samples: false
        - path: google/cloud/alloydb/connectors/v1beta
          proto_only: true
          samples: false
      product_documentation_override: https://cloud.google.com/alloydb/docs
      rest_documentation: https://cloud.google.com/alloydb/docs/reference/rest
```

### PR DESCRIPTION
**Pull request by zhumin8**
Adds a hardcoded transport override for `alloydb-connectors`. This is used only for .repo-metadata.json and documentation to minimize generation diff, no affect on Java code generation because this is an proto-only library. 
More context in #5554.

Fix #5554

### CODE REVIEW

File: tool/cmd/migrate/java_module.go [hunk 1]
```diff
@@ -110,6 +110,10 @@ var (
 			gapicArtifactID: "google-cloud-storage-control",
 		},
 	}
+
```
Comment (noahdietz) [inline tool/cmd/migrate/java_module.go:113]: Nit: Can you add a comment similar to the one in the PR description as to what this is for and why its OK?

File: tool/cmd/migrate/java_module.go [hunk 2]
```diff
@@ -110,6 +110,10 @@ var (
...
+	javaTransportOverrides = map[string]string{
```
Comment (noahdietz) [inline tool/cmd/migrate/java_module.go:114]: Is this something we will need to fix/cleanup somehow in the future? Not sure if it is worth filing a TODO for or not, I'll let you be the judge.

Comment (zhumin8) [reply tool/cmd/migrate/java_module.go:114]: Good point. Added a issue link to the config (internal/config/language.go).

**Comment by noahdietz** [comment]
Looks like the TODO snuck its way into the comments that go-generate consumes

**Comment by noahdietz** [comment]
> Looks like the TODO snuck its way into the comments that go-generate consumes

Consider adding it after the property so it doesn't show up in the generated documentation? I'm not sure how to make it not appear there :)

**Comment by zhumin8** [comment]
updated the doc. Not terrible to have TODO there, we already got a bunch.

**Review by noahdietz — APPROVED** [review]
