### PR TITLE
fix: ignore version override if library flag is not specified

### LINKED ISSUE #1823: In release init command, version override should be ignored if `library` flag is not specified

### PR DESCRIPTION
**Pull request by JoeWang1127**
Fixes #1823

### CODE REVIEW

File: internal/librarian/release_init.go [hunk 1]
```diff
@@ -188,28 +194,25 @@ func (r *initRunner) runInitCommand(ctx context.Context, outputDir string) error
...
-	library := state.Libraries[index]
-	updatedLibrary, err := getChangesOf(r.repo, library)
+// updateLibrary updates the given library in the following way:
+//
+// 1. Get the library's commit history in the given git repository.
+//
+// 2. Override the library version if overrideVersion is true.
+//
+// 3. Set the library's release trigger to true.
+func updateLibrary(repo gitrepo.Repository, library *config.LibraryState, libraryVersion string, overrideVersion bool) (*config.LibraryState, error) {
```
Comment (codyoss) [inline internal/librarian/release_init.go:204]: I think this can be simplified to just pass `""` when `overrideVersion` would be false -- I don't think we need both fields.
